### PR TITLE
June Roll

### PR DESCRIPTION
**Pull request by alcueca**
# Proposal
Activate the DAI, USDC, ETH and FRAX December series on mainnet using yieldspace-tv, and roll the respective strategies from June to December

# Background
On June 24th 2022 all June series matured, and the YSDAI6MMS, YSUSDC6MMS, YSETH6MMS and YSFRAX6MMs strategies stopped accruing fees. New yieldspace-tv pools are going to be used for the December series, with eTokens as a yield-bearing token to provide extra returns to LPs.

# Details
Here are the steps:
1. Deploy Roller to use flash loans if the Joins don't have enough assets to redeem all fyToken in the rolled pools.
2. Deploy fyToken contracts for FYDAI2212, FYUSDC2212, FYETH2212 and FYFRAX2212.
3. Deploy respective pool contracts. FRAX won't use an underlying Euler token.
4. Governance proposal
    1. Orchestrate pools
    2. Orchestrate roller
    3. Add new series
    4. Add ilks to the new series
    5. Initialize new pools
    6. Roll the strategies to the next pool

We would be deploying the fyTokens & pools using the [add script link](), with [add config link]():

```
// Time stretch to be set in the PoolFactory prior to pool deployment
export const timeStretch: Map<string, BigNumber> = new Map([
  [FYETH2212, ONE64.div(secondsInOneYear.mul(25))],
  [FYDAI2212, ONE64.div(secondsInOneYear.mul(45))],
  [FYUSDC2212, ONE64.div(secondsInOneYear.mul(55))],
  [FYFRAX2212, ONE64.div(secondsInOneYear.mul(20))],
])

// Sell base to the pool fee, as fp4
export const g1: number = 9000

// seriesId, underlyingId, chiOracleAddress, joinAddress, maturity, name, symbol
export const fyTokenData: Array<[string, string, string, string, number, string, string]> = [
  [FYETH2212, ETH, protocol.get(COMPOUND) as string, joins.get(ETH) as string, EODEC22, 'FYETH2212', 'FYETH2212'],
  [FYDAI2212, DAI, protocol.get(COMPOUND) as string, joins.get(DAI) as string, EODEC22, 'FYDAI2212', 'FYDAI2212'],
  [FYUSDC2212, USDC, protocol.get(COMPOUND) as string, joins.get(USDC) as string, EODEC22, 'FYUSDC2212', 'FYUSDC2212'],
  [
    FYFRAX2212,
    FRAX,
    protocol.get(ACCUMULATOR) as string,
    joins.get(FRAX) as string,
    EODEC22,
    'FYFRAX2212',
    'FYFRAX2212',
  ],
]

// Parameters to deploy pools with, a pool being identified by the related seriesId
// seriesId, baseAddress, fyTokenAddress, ts (time stretch), g1 (Sell base to the pool fee)
export const yvPoolData: Array<[string, string, string, BigNumber, number]> = [
  //  [FYUSDC2212, assets.get(YVUSDC) as string, newFYTokens.get(FYUSDC2212) as string, timeStretch, g1],
  //  [FYDAI2212, assets.get(YVDAI) as string, newFYTokens.get(FYDAI2212) as string, timeStretch, g1],
]

// Parameters to deploy pools with, a pool being identified by the related seriesId
// seriesId, baseAddress, fyTokenAddress, ts (time stretch), g1 (Sell base to the pool fee)
export const nonTVPoolData: Array<[string, string, string, BigNumber, number]> = [
  [
    FYFRAX2212,
    assets.get(FRAX) as string,
    newFYTokens.get(FYFRAX2212) as string,
    timeStretch.get(FYFRAX2212) as BigNumber,
    g1,
  ],
]

// Parameters to deploy pools with, a pool being identified by the related seriesId
// seriesId, baseAddress, fyTokenAddress, ts (time stretch), g1 (Sell base to the pool fee)
export const ePoolData: Array<[string, string, string, string, BigNumber, number]> = [
  [
    FYETH2212,
    eulerAddress,
    assets.get(EWETH) as string,
    newFYTokens.get(FYETH2212) as string,
    timeStretch.get(FYETH2212) as BigNumber,
    g1,
  ],
  [
    FYDAI2212,
    eulerAddress,
    assets.get(EDAI) as string,
    newFYTokens.get(FYDAI2212) as string,
    timeStretch.get(FYDAI2212) as BigNumber,
    g1,
  ],
  [
    FYUSDC2212,
    eulerAddress,
    assets.get(EUSDC) as string,
    newFYTokens.get(FYUSDC2212) as string,
    timeStretch.get(FYUSDC2212) as BigNumber,
    g1,
  ],
]

// Amounts to initialize pools with, a pool being identified by the related seriesId
// seriesId, initAmount
export const poolsInit: Array<[string, string, BigNumber, BigNumber]> = [
  [FYETH2212, ETH, WAD.div(10), BigNumber.from('0')],
  [FYDAI2212, DAI, WAD.mul(100), BigNumber.from('0')],
  [FYUSDC2212, USDC, ONEUSDC.mul(100), BigNumber.from('0')],
  [FYFRAX2212, FRAX, WAD.mul(100), BigNumber.from('0')],
]

// Ilks to accept for each series
// seriesId, accepted ilks
export const seriesIlks: Array<[string, string[]]> = [
  [FYETH2212, [ETH, DAI, USDC, WBTC, WSTETH, LINK, ENS, UNI, FRAX]],
  [FYDAI2212, [ETH, DAI, USDC, WBTC, WSTETH, LINK, ENS, UNI, FRAX]],
  [FYUSDC2212, [ETH, DAI, USDC, WBTC, WSTETH, LINK, ENS, UNI, FRAX, YVUSDC]],
  [FYFRAX2212, [ETH, DAI, USDC, WBTC, WSTETH, LINK, ENS, UNI, FRAX]],
]

/// Parameters to roll each strategy
/// @param strategyId
/// @param nextSeriesId
/// @param buffer Amount of base sent to the Roller to make up for market losses when using a flash loan for rolling
/// @param lender ERC3156 flash lender used for rolling
/// @param fix If true, transfer one base wei to the pool to allow the Strategy to start enhanced TV pools
export const rollData: Array<[string, string, BigNumber, string, boolean]> = [
  [YSETH6MJD, FYETH2212, ZERO, ZERO_ADDRESS, true],
  [YSDAI6MJD, FYDAI2212, WAD.mul(10000), flashMintModule, true],
  [YSUSDC6MJD, FYUSDC2212, ZERO, ZERO_ADDRESS, true],
  [YSFRAX6MJD, FYFRAX2212, ZERO, ZERO_ADDRESS, false],
]
```

# Testing
The change has been deployed on a [tenderly mainnet fork](https://dashboard.tenderly.co/Yield/v2/fork/45fc251f-fd4f-479c-aba8-cdfc9bb82653) and passed [UX testing](https://docs.google.com/spreadsheets/d/1H--DrP57ikEXlrvhp44t-7rFGYYrPZEpajSROfI8HWA/edit#gid=513492953)

### CODE REVIEW

**Comment by devtooligan** [comment]
txn hash for mainnet roll proposal
0x22ed3eb555f1415f1d41fb312b56356e389d3c1dcbf6445b0bb68f292a1df25d

**Comment by alcueca** [comment]
New proposal: `0x5c82741372e5fc4885ec654bdbee236c40fe50f7415d806ab2bba2ae95d1b35a`

**Comment by alcueca** [comment]
[State Changes Diff on Tenderly](https://dashboard.tenderly.co/Yield/v2/fork/dfaf2111-65d1-4753-a173-5f5a92c929fb/simulation/db455c57-f8f2-439a-8ff0-1f3117cfe2f0/state-diff)

**Comment by alcueca** [comment]
- RoleGranted events reviewed to grant roles only to contracts in the Yield Protocol.
- IntegrationAdded events reviewed to include only the new Pools.
- PoolAdded events reviewed to include only the new Pools
- TokenAdded events reviewed to include only the Yield Protocol contracts

[[Analysis of asset balances](https://docs.google.com/spreadsheets/d/1wDWK1XjixQ_F-0OITGfn3lL6iKES47k_6eSIlBub9Kg/edit#gid=0)](https://docs.google.com/spreadsheets/d/1wDWK1XjixQ_F-0OITGfn3lL6iKES47k_6eSIlBub9Kg/edit#gid=0)

**Comment by alcueca** [comment]
Queued for approval on multisig as #46

**Comment by alcueca** [comment]
Delayed until completion of Euler's [EIP-14](https://forum.euler.finance/t/eip-14-contract-upgrades/305)

**Comment by alcueca** [comment]
Euler was fixed bypassing governance.

Here are the diffs:
https://euler-xyz.github.io/euler-contracts-upgrade-diffs/read-only-reentrancy-hotfix/EToken.html

https://euler-xyz.github.io/euler-contracts-upgrade-diffs/read-only-reentrancy-hotfix/DToken.html

Fix Transaction hash: 0x3179d61854874628d578d7e3477ab034588a103b80d916e246085cccbdd375c4

[Executed](https://etherscan.io/tx/0x89f85af7b18779a7079cbcc14340ae18d4b1a1372f420ce4b642cf549a529e81)

**Pull request merged**
