### PR TITLE
Lower dust on FRAX series

### PR DESCRIPTION
**Pull request by devtooligan**
# Proposal
Lower the dust levels

# Background
The dust (min debt) level for FRAX borrowing is set to 5000 (USD VALUE) currently, which now too high to incentivize smaller vaults. Liquidating a vault costs $20 USD at 13 Gwei.

# Details
The [updateDust.ts](https://github.com/yieldprotocol/environments-v2/pull/293/files#diff-eff1c2a858cba3323fcc396b80daa2aad677ce28500f9825ddcf7a4e1bc29856) script will be used, with this input:
```
/// @notice Minimum debt limits
/// @param base identifier (bytes6 tag)
/// @param collateral identifier (bytes6 tag)
/// @param minimum vault debt, modified by decimals
export const newDebtMin: Array<[string, string, number]> = [
  [FRAX, FRAX, 0],
  [FRAX, ETH, 1000],
  [FRAX, DAI, 1000],
  [FRAX, USDC, 1000],
  [FRAX, WBTC, 1000],
  [FRAX, WSTETH, 1000],
  [FRAX, LINK, 1000],
  [FRAX, UNI, 1000],

]
```
# Testing
The change has been tested on a mainnet fork and a Tenderly fork by running [updateDust.ts](https://github.com/yieldprotocol/environments-v2/pull/293/files#diff-eff1c2a858cba3323fcc396b80daa2aad677ce28500f9825ddcf7a4e1bc29856) first, followed by [updateDust.test.ts](https://github.com/yieldprotocol/environments-v2/pull/293/files#diff-eff1c2a858cba3323fcc396b80daa2aad677ce28500f9825ddcf7a4e1bc29856) to verify that the changes were made.
``` bash
 bash scripts/governance/update/updateDust/updateDust.sh                                      ✔
++ dirname scripts/governance/update/updateDust/updateDust.sh
+ HERE=scripts/governance/update/updateDust
+ export CONF=/Users/devtooligan/dev/yield/environments-v2/scripts/governance/update/updateDust/updateDust.config
+ CONF=/Users/devtooligan/dev/yield/environments-v2/scripts/governance/update/updateDust/updateDust.config
+ RUN='npx hardhat run --network tenderly'
+ npx hardhat run --network tenderly scripts/governance/update/updateDust/updateDust.ts
Impersonated 0xfe90d993367bc93D171A5ED88ab460759DE2bED6

Debt Limits (dust)
FRAX/FRAX0 -> 0
FRAX/ETH5000 -> 1000
FRAX/DAI5000 -> 1000
FRAX/USDC5000 -> 1000
FRAX/WBTC5000 -> 1000
FRAX/WSTETH5000 -> 1000
FRAX/LINK5000 -> 1000
FRAX/UNI5000 -> 1000
Impersonated 0xfe90d993367bc93D171A5ED88ab460759DE2bED6
Proposal: 0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3
Proposing
Developer: 0xfe90d993367bc93D171A5ED88ab460759DE2bED6

Calldata:
0xca02753a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000004400000000000000000000000000000000000000000000000000000000000000560000000000000000000000000000000000000000000000000000000000000068000000000000000000000000000000000000000000000000000000000000007a0000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000313800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000303000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000303100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000303200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000303300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000303600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3138000000000000000000000000000000000000000000000000000000000000313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000
Proposed 0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3
+ npx hardhat run --network tenderly scripts/governance/update/updateDust/../../../../shared/approve.ts
Impersonated 0xd659565b84bcfcb23b02ee13e46cb51429f4558a
Proposal: 0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3
Approving
Approved: 0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3
advancing time by 172800 seconds (2 days)
+ npx hardhat run --network tenderly scripts/governance/update/updateDust/../../../../shared/execute.ts
Impersonated 0xfe90d993367bc93D171A5ED88ab460759DE2bED6
Proposal: 0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3
Executing
Estimated gas: 161694 - ETH Balance: 1.0
Executed 0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3
+ npx hardhat run --network tenderly scripts/governance/update/updateDust/updateDust.test.ts
Impersonated 0xfe90d993367bc93D171A5ED88ab460759DE2bED6

Post deployment state testing
=============================

Debt Limits (dust)
Success! FRAX/FRAX set to: 0
Success! FRAX/ETH set to: 1000
Success! FRAX/DAI set to: 1000
Success! FRAX/USDC set to: 1000
Success! FRAX/WBTC set to: 1000
Success! FRAX/WSTETH set to: 1000
Success! FRAX/LINK set to: 1000
Success! FRAX/UNI set to: 1000

```

### CODE REVIEW

**Comment by alcueca** [comment]
`dust` for FRAX/FRAX should be zero.
`dust` for FRAX/WSTETH is missing, should be 1000.

**Comment by alcueca** [comment]
Proposed again: `0xc0454a68bae4091cc7828f712b11befbf84b77db8d3028c19cb557da80e5d0f3`

**Comment by alcueca** [comment]
[Execution on fork](https://dashboard.tenderly.co/Yield/v2/fork/065584fd-6f8b-4078-94e4-b255acc95ef9/simulation/9a31f7cc-fff4-46f5-9b7d-d69ed67832d2)

**Comment by devtooligan** [comment]
[executed](https://github.com/yieldprotocol/environments-v2/pull/293/#issuecomment-1370050465)

**Pull request merged**
