### PR TITLE
`NotionalLever` proposal

### PR DESCRIPTION
**Pull request by iamsahu**
# Proposal

Deploy a Notional lever which allows user to create a leveraged position of fCash tokens

# Details

In this proposal we are going to deploy Notional lever contract and orchestrate it to give required permissions on `Giver`.

Steps:

1. Deploy Notional lever contract (no need for governance proposal)
2. Orchestrate Notional Lever
   1. Grant permission on Giver for give to the lever
   2. Grant permission on Giver for seize to the lever

Configuration Parameters:

```
// ----- deployment parameters -----
export const contractDeployments: ContractDeployment[] = [
  {
    addressFile: 'protocol.json',
    name: YIELD_NOTIONAL_LEVER,
    contract: 'YieldNotionalLever',
    args: [() => protocol().getOrThrow(GIVER)],
  },
]

```

# Testing

Testing was done on tenderly & local forks

### CODE REVIEW

**Comment by iamsahu** [comment]
Proposal for flashFee update: `0x714e46fec66f2beedac12837294ed049f24eeb8ab980da11935de5b90d54a6dd`

[TenderlyFork](https://dashboard.tenderly.co/Yield/v2/fork/90739cfc-5a02-4a8d-927c-7d63b213f4aa)

**Comment by iamsahu** [comment]
Proposal for NotionalLever: `0x1c879767afc267a19271b05a6a780bd2befe5dd84114fd64a44cad625a5e0b55`
[Tenderly Fork](https://dashboard.tenderly.co/Yield/v2/fork/21b59300-aa11-40a7-9465-bb75e357d5b9)

**Comment by alcueca** [comment]
The flashFee update is already part of the stEthLever proposal.

Thankfully, since you have broken this proposal in two parts, we can just drop the flashFee update and we don't need to resubmit anything.

**Comment by iamsahu** [comment]
[Executed](https://etherscan.io/tx/0xa216dbc215d806380c481c194b7857cc25d1e77b11001b3a2324fb1fdf04e022)

**Pull request merged**
