### PR TITLE
🦀 Crab as a collateral

### PR DESCRIPTION
**Pull request by iamsahu**
# Proposal

Enable crab strategy token as a collateral.

# Background

# Details

Following steps would be taken to get the strategy token as a collateral:

1. Deploy CrabOracle (no need for governance approval)
2. Deploy joins for crab assets (no need for governance approval)
3. Governance Proposal
   1. Update UniswapOracle with OSQTH source
   2. Update compositeOracle sources
   3. Update compositeOracle paths
   4. Orchestrate the new crab token joins
   5. Add crab tokens as Assets
   6. Make crab tokens as ilks
   7. Add crab tokens as ilks in series

Here are the config parameters:

```
export const uniswapOracleSources: [string, string, string, number][] = [
  [ETH, OSQTH, '0x82c427AdFDf2d245Ec51D8046b41c4ee87F0d29C', 100],
]

/// @notice Sources that will be added to the Composite Oracle
/// @param Base asset identifier (bytes6 tag)
/// @param Quote asset identifier (bytes6 tag)
/// @param Address for the source
export const compositeSources: Array<[string, string, string]> = [[CRAB, ETH, protocol().getOrThrow(CRAB_ORACLE)!]]

export const newCompositePaths: Array<[string, string, Array<string>]> = [
  [CRAB, USDC, [ETH]],
  [CRAB, DAI, [ETH]],
]

/// @notice Configure an asset as an ilk for a base using the Chainlink Oracle
/// @param Base asset identifier (bytes6 tag)
/// @param Ilk asset identifier (bytes6 tag)
/// @param Collateralization ratio as a fixed point number with 6 decimals
/// @param Debt ceiling, modified by decimals
/// @param Minimum vault debt, modified by decimals
/// @param Decimals to append to debt ceiling and minimum vault debt.
export const newCrabLimits: Array<[string, string, number, number, number, number]> = [
  [ETH, CRAB, 1400000, 250, 1, 18],
  [USDC, CRAB, 1330000, 250000, 1000, 6],
  [DAI, CRAB, 1330000, 250000, 1000, 18],
]

/// @notice Ilks to accept for series
/// @param series identifier (bytes6 tag)
/// @param newly accepted ilks (array of bytes6 tags)
export const seriesIlks: Array<[string, string[]]> = [
  [FYETH2212, [CRAB]],
  [FYUSDC2212, [CRAB]],
  [FYDAI2212, [CRAB]],
  [FYETH2303, [CRAB]],
  [FYUSDC2303, [CRAB]],
  [FYDAI2303, [CRAB]],
]

/// Auction configuration for each asset pair
/// @param baseId assets in scope as underlying for vaults to be auctioned
/// @param ilkId assets in scope as collateral for vaults to be auctioned
/// @param duration time that it takes for the auction to offer maximum collateral
/// @param vaultProportion proportion of a vault that will be auctioned at a time
/// @param collateralProportion proportion of the collateral that will be paid out
/// at the begining of an auction
/// @param max If the aggregated collateral under auction for vaults of this pair
/// exceeds this number, no more auctions of for this pair can be started.
export const v2Limits: AuctionLineAndLimit[] = [
  // DAI
  {
    baseId: ETH,
    ilkId: CRAB,
    duration: 600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.78571429'), // 110 / 140
    max: parseUnits('1000'),
  },
  {
    baseId: USDC,
    ilkId: CRAB,
    duration: 600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.82706767'), // 110 / 133
    max: parseUnits('1000'),
  },
  {
    baseId: DAI,
    ilkId: CRAB,
    duration: 600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.82706767'), // 110 / 133
    max: parseUnits('1000'),
  },
]

```

# Testing

The change has been deployed on a mainnet fork [here](https://dashboard.tenderly.co/Yield/v2/fork/b69810b6-1c34-4eaa-bf3c-250e24717034) with the following output:

```
+ npx hardhat run --network tenderly ./scripts/governance/add/addCollateral/addCrabCollateral/../../../../../shared/deploy.ts
Impersonated 0xfe90d993367bc93D171A5ED88ab460759DE2bED6
Reusing crabOracle at: 0x35d753A30a750C0291CD86baEDef7d27d55879F9
Reusing 0x333800000000 at: 0xBea1401C7Fed8e64B2AF9B21Da53293E01D81d32
+ npx hardhat run --network tenderly ./scripts/governance/add/addCollateral/addCrabCollateral/addCrab.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
┌─────────┬──────────────────┬──────────────────────────────────────────────┬──────────────────────────────────────────────┐
│ (index) │        0         │                      1                       │                      2                       │
├─────────┼──────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┤
│    0    │ '0x333800000000' │ '0x3B960E47784150F5a63777201ee2B15253D713e8' │ '0xBea1401C7Fed8e64B2AF9B21Da53293E01D81d32' │
└─────────┴──────────────────┴──────────────────────────────────────────────┴──────────────────────────────────────────────┘
Setting up 0x82c427AdFDf2d245Ec51D8046b41c4ee87F0d29C as the source for 0x303000000000/0x333900000000 at 0x358538ea4F52Ac15C551f88C701696f6d9b38F3C
Adding 0x333800000000/0x303000000000 from 0x35d753A30a750C0291CD86baEDef7d27d55879F9
pair: 38/00 -> 0x35d753A30a750C0291CD86baEDef7d27d55879F9
[path: 38/02 -> 0x303000000000],
[path: 38/01 -> 0x303000000000],
join.grantRole(ROOT, cloak)
Using asset at 0x3B960E47784150F5a63777201ee2B15253D713e8
Using join at 0xBea1401C7Fed8e64B2AF9B21Da53293E01D81d32
Adding asset 0x333800000000 at 0x3B960E47784150F5a63777201ee2B15253D713e8 with join 0xBea1401C7Fed8e64B2AF9B21Da53293E01D81d32
cloak.plan(join, join(38)): 0xf42240f4ed416db24e0ea660de396facee794afb848e747d1b73f75e8e395c3c
Witch#setLineAndLimit(38, 00, 600, 500000000000000000, 750000000000000000, 1000000000000000000000000)
Witch#setLineAndLimit(38, 02, 600, 1000000000000000000, 954545454500000000, 1000000000000000000000000)
Witch#setLineAndLimit(38, 01, 600, 1000000000000000000, 954545454500000000, 1000000000000000000000000)
Allowing witch to exit join: 0xBea1401C7Fed8e64B2AF9B21Da53293E01D81d32
cloak.plan(witch, exit(38)): 0x6204ea1b53c251b50dff4fe84032f609cf88832fcd0149a491d104af7146498e
Adding for 00/38 from 0xA81414a544D0bd8a28257F4038D3D24B08Dd9Bb4
Adding for 02/38 from 0xA81414a544D0bd8a28257F4038D3D24B08Dd9Bb4
Adding for 01/38 from 0xA81414a544D0bd8a28257F4038D3D24B08Dd9Bb4
Updating 0x303030380000 series with 0x333800000000 ilks
addIlks 0008: 0x333800000000
Updating 0x303230380000 series with 0x333800000000 ilks
addIlks 0208: 0x333800000000
Updating 0x303130380000 series with 0x333800000000 ilks
addIlks 0108: 0x333800000000
Updating 0x303030390000 series with 0x333800000000 ilks
addIlks 0009: 0x333800000000
Updating 0x303230390000 series with 0x333800000000 ilks
addIlks 0209: 0x333800000000
Updating 0x303130390000 series with 0x333800000000 ilks
addIlks 0109: 0x333800000000
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Proposal: 0xe0bc51a9b2fdb07caae80a3b30460f2e68c223cfed1a3bed03052deae15793ef
Proposing
Developer: 0xC7aE076086623ecEA2450e364C838916a043F9a8

Calldata:
0xca02753a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d00000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000004a000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000660000000000000000000000000000000000000000000000000000000000000078000000000000000000000000000000000000000000000000000000000000008a000000000000000000000000000000000000000000000000000000000000009600000000000000000000000000000000000000000000000000000000000000a800000000000000000000000000000000000000000000000000000000000000b400000000000000000000000000000000000000000000000000000000000000ce00000000000000000000000000000000000000000000000000000000000000e200000000000000000000000000000000000000000000000000000000000000f6000000000000000000000000000000000000000000000000000000000000010a0000000000000000000000000000000000000000000000000000000000000116000000000000000000000000000000000000000000000000000000000000012e000000000000000000000000000000000000000000000000000000000000013c000000000000000000000000000000000000000000000000000000000000014c000000000000000000000000000000000000000000000000000000000000015e000000000000000000000000000000000000000000000000000000000000016c000000000000000000000000000000000000000000000000000000000000017c000000000000000000000000000000000000000000000000000000000000018e000000000000000000000000000000000000000000000000000000000000019c00000000000000000000000000000000000000000000000000000000000001ac00000000000000000000000000000000000000000000000000000000000001be00000000000000000000000000000000000000000000000000000000000001ce00000000000000000000000000000000000000000000000000000000000001de00000000000000000000000000000000000000000000000000000000000001ee00000000000000000000000000000000000000000000000000000000000001fe000000000000000000000000000000000000000000000000000000000000020e0000000000000000000000000358538ea4f52ac15c551f88c701696f6d9b38f3c00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000084e46504183030000000000000000000000000000000000000000000000000000000000000333900000000000000000000000000000000000000000000000000000000000000000000000000000000000082c427adfdf2d245ec51d8046b41c4ee87f0d29c00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000000000000000000000035d753a30a750c0291cd86baedef7d27d55879f90000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006468284fd4333800000000000000000000000000000000000000000000000000000000000030300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006492b45d9c3338000000000000000000000000000000000000000000000000000000000000303000000000000000000000000000000000000000000000000000000000000000000000000000000000000035d753a30a750c0291cd86baedef7d27d55879f900000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb4000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a460509e5f3338000000000000000000000000000000000000000000000000000000000000303200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000001303000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb4000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a460509e5f3338000000000000000000000000000000000000000000000000000000000000303100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000001303000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000bea1401c7fed8e64b2af9b21da53293e01d81d3200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044de02cde70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000aa7b33685e9730b4d700b8f3f190eca5ec4cf10600000000000000000000000000000000000000000000000000000000000000000000000000000000bea1401c7fed8e64b2af9b21da53293e01d81d32000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4effae35300000000000000000000000000000000000000000000000000000000000000400000000000000000000000006cb18ff2a33e981d1e38a663ca056c0a5265066a0000000000000000000000000000000000000000000000000000000000000002ceae3abd0000000000000000000000000000000000000000000000000000000012e5ff7700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006cb18ff2a33e981d1e38a663ca056c0a5265066a0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004449c29d2b3338000000000000000000000000000000000000000000000000000000000000000000000000000000000000bea1401c7fed8e64b2af9b21da53293e01d81d3200000000000000000000000000000000000000000000000000000000000000000000000000000000aa7b33685e9730b4d700b8f3f190eca5ec4cf10600000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000124de8a06670000000000000000000000006cb18ff2a33e981d1e38a663ca056c0a5265066a000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bea1401c7fed8e64b2af9b21da53293e01d81d3200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002ceae3abd0000000000000000000000000000000000000000000000000000000012e5ff77000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c43fa3c32233380000000000000000000000000000000000000000000000000000000000003030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000025800000000000000000000000000000000000000000000000006f05b59d3b200000000000000000000000000000000000000000000000000000a688906bd8b000000000000000000000000000000000000000000000000d3c21bcecceda10000000000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c43fa3c3223338000000000000000000000000000000000000000000000000000000000000303200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002580000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000d3f3a08916fb10000000000000000000000000000000000000000000000d3c21bcecceda10000000000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c43fa3c3223338000000000000000000000000000000000000000000000000000000000000303100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002580000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000d3f3a08916fb10000000000000000000000000000000000000000000000d3c21bcecceda100000000000000000000000000000000000000000000000000000000000000000000000000000000000000bea1401c7fed8e64b2af9b21da53293e01d81d3200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044de02cde712e5ff770000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c40000000000000000000000000000000000000000000000000000000000000000000000000000000000aa7b33685e9730b4d700b8f3f190eca5ec4cf10600000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000104de8a066700000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bea1401c7fed8e64b2af9b21da53293e01d81d320000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000112e5ff770000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006468284fd4303000000000000000000000000000000000000000000000000000000000000033380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000848ef6bdfa30300000000000000000000000000000000000000000000000000000000000003338000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000155cc000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3030000000000000000000000000000000000000000000000000000000000000333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fa0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006468284fd4303200000000000000000000000000000000000000000000000000000000000033380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000848ef6bdfa30320000000000000000000000000000000000000000000000000000000000003338000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000144b5000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b30320000000000000000000000000000000000000000000000000000000000003338000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d09000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006468284fd4303100000000000000000000000000000000000000000000000000000000000033380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000848ef6bdfa30310000000000000000000000000000000000000000000000000000000000003338000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000144b5000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b30310000000000000000000000000000000000000000000000000000000000003338000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d09000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303030380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303230380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303130380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303030390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303230390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303130390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001333800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Proposed 0xe0bc51a9b2fdb07caae80a3b30460f2e68c223cfed1a3bed03052deae15793ef
+ npx hardhat run --network tenderly ./scripts/governance/add/addCollateral/addCrabCollateral/../../../../../shared/approve.ts
Impersonated 0xd659565b84bcfcb23b02ee13e46cb51429f4558a
Proposal: 0xe0bc51a9b2fdb07caae80a3b30460f2e68c223cfed1a3bed03052deae15793ef
Approving
Approved: 0xe0bc51a9b2fdb07caae80a3b30460f2e68c223cfed1a3bed03052deae15793ef
advancing time by 172800 seconds (2 days)
+ npx hardhat run --network tenderly ./scripts/governance/add/addCollateral/addCrabCollateral/../../../../../shared/execute.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Proposal: 0xe0bc51a9b2fdb07caae80a3b30460f2e68c223cfed1a3bed03052deae15793ef
Executing
Estimated gas: 1246741 - ETH Balance: 1.0
Executed 0xe0bc51a9b2fdb07caae80a3b30460f2e68c223cfed1a3bed03052deae15793ef
```

Here is the output of the tests:

```
+ npx hardhat run --network localhost ./scripts/governance/add/addCollateral/addCrabCollateral/addCrab.test.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Impersonated 0xa1cab67a4383312718a5799eaa127906e9d4b19e
series: 0x303030380000
ilk: 0x333800000000
vault: 0x8bc0931670752212c1c18bd0
posting 1432276598045668562 ilk out of 191234979197564433029
borrowing 1000000000000000000 FYETH2212
posted and borrowed
repaying 1000000000000000000 FYETH2212 and withdrawing 1432276598045668562 ilk
repaid and withdrawn
Impersonated 0xa1cab67a4383312718a5799eaa127906e9d4b19e
series: 0x303230380000
ilk: 0x333800000000
vault: 0x4ef4f757baa168d9c7ed27d0
posting 1064957076099089140 ilk out of 191234979197564433029
borrowing 1000000000 FYUSDC2212
posted and borrowed
repaying 1000000000 FYUSDC2212 and withdrawing 1064957076099089140 ilk
repaid and withdrawn
Impersonated 0xa1cab67a4383312718a5799eaa127906e9d4b19e
series: 0x303130380000
ilk: 0x333800000000
vault: 0xf7c4d2a21ae257c19c10105a
posting 1065271587875258055 ilk out of 191234979197564433029
borrowing 1000000000000000000000 FYDAI2212
posted and borrowed
repaying 1000000000000000000000 FYDAI2212 and withdrawing 1065271587875258055 ilk
repaid and withdrawn
Impersonated 0xa1cab67a4383312718a5799eaa127906e9d4b19e
series: 0x303030390000
ilk: 0x333800000000
vault: 0xcba50fe7f1703319325dfe3f
posting 1432276598045668562 ilk out of 191234979197564433029
borrowing 1000000000000000000 FYETH2303
posted and borrowed
repaying 1000000000000000000 FYETH2303 and withdrawing 1432276598045668562 ilk
repaid and withdrawn
Impersonated 0xa1cab67a4383312718a5799eaa127906e9d4b19e
series: 0x303230390000
ilk: 0x333800000000
vault: 0x41ef534e9c04d35786d4d19b
posting 1064957076099089140 ilk out of 191234979197564433029
borrowing 1000000000 FYUSDC2303
posted and borrowed
repaying 1000000000 FYUSDC2303 and withdrawing 1064957076099089140 ilk
repaid and withdrawn
Impersonated 0xa1cab67a4383312718a5799eaa127906e9d4b19e
series: 0x303130390000
ilk: 0x333800000000
vault: 0xc6c25f962ef5464546ea61c9
posting 1065271587875258055 ilk out of 191234979197564433029
borrowing 1000000000000000000000 FYDAI2303
posted and borrowed
repaying 1000000000000000000000 FYDAI2303 and withdrawing 1065271587875258055 ilk
repaid and withdrawn
```

### CODE REVIEW

**Review by alcueca — APPROVED** [review]
The limits look fine. They are set in base terms, so they are [1000..250000] USDC, [1..250] ETH, and [1000..250000] DAI.

**Comment by iamsahu** [comment]
Proposed: `0xda86763745810c0638183f71587b07aee540c1aea7cd0d0ab47052f478280925`
With the transaction [here](https://etherscan.io/tx/0x3abcce29b6c02af601228fb910939da5afab71ef04df22f64bddb27d3e041288)

[Here](https://dashboard.tenderly.co/Yield/v2/fork/d76d6e1c-0913-4279-9fcc-773959ad0750) is the tenderly fork with approve & executed.

**Comment by alcueca** [comment]
@iamsahu, the CrabOracle and CrabJoin need to be [added in Tenderly](https://dashboard.tenderly.co/Yield/v2/contracts).

**Comment by iamsahu** [comment]
To reduce the surface of attack the Join was redeployed with no flashLoan functionality. Also, the asset configuration was modified to make it work new Witch in the future.

Proposed: `0x383ebc0902d685ad27e85e7120ec2de56ea9f1ed126427f845828fd1a0ed3036`

[Here](https://dashboard.tenderly.co/Yield/v2/fork/1a956d00-12b7-41cf-8d83-73fa534c0991) is the tenderly fork of approve & execute.

**Comment by iamsahu** [comment]
Unfortunately due to another config error it had to be proposed again: `0xd151da92c39087102d2993fa3fc233c1deaaa40e4938be3a989caf85438e917d`

[Here](https://dashboard.tenderly.co/Yield/v2/fork/3ff60b27-5a54-4d10-8266-56ef3cc6ef76) is the tenderly fork of approve & execute

**Review by alcueca — APPROVED** [review]
Good to go, [proposal analysis](https://www.notion.so/YPP-86-Crab-strategy-tokens-as-collateral-c664dfebab584692a7694ae414c2ad86)

**Comment by iamsahu** [comment]
YPP-86 has been proposed again to update the witch parameters: `0x5ba47fa7a8f963b1255d5a94daab2b771be2011c635be59bdb674c1388b74d23`
[Here](https://dashboard.tenderly.co/Yield/v2/fork/9483d101-6d2a-471d-a7df-79a6744c5473) is the approve & execute fork.

**Comment by iamsahu** [comment]
[Executed](https://etherscan.io/tx/0xfda478dbb8b8d9a6d9b2f73b4b84d463f10dd8e0d584fb8fad76bad9ea64b4db)

**Comment by iamsahu** [comment]
[Executed](https://etherscan.io/tx/0xfda478dbb8b8d9a6d9b2f73b4b84d463f10dd8e0d584fb8fad76bad9ea64b4db)

**Pull request merged**
