### PR TITLE
Deploy HealerModule and add to Ladle

### PR DESCRIPTION
**Pull request by Sabnock01**
# Proposal 
Deploy a HealerModule to the Ladle that allows any user to add collateral or repay debt to any vault. 

# Background
To be used with the Mero Finance integration. The YieldHandler used by Mero allows for collateral top-up actions for vaults approaching liquidation. The HealerModule adds the capacity for this to be accomplished.  

# Details
The proposal includes two mainnet executions...
1. Deploying the HealerModule using [this script](https://github.com/yieldprotocol/environments-v2/blob/7fa485f4dd0694aec6becb0f2fa1b57539b03056/scripts/governance/deploy/deployHealer.ts). The HealerModule takes the Cauldron and WETH addresses as constructor arguments. 
2. Add the HealerModule to the Ladle using [this script](https://github.com/yieldprotocol/environments-v2/blob/7fa485f4dd0694aec6becb0f2fa1b57539b03056/scripts/governance/add/addModule/addModule.ts).

# Testing
The testing is done on [this test contract](https://github.com/yieldprotocol/vault-v2/blob/master/packages/foundry/contracts/test/modules/HealerModule.t.sol) which uses a mainnet fork

```
$ forge test -c contracts/test/modules/
[⠊] Compiling...
[⠘] Compiling 28 files with 0.8.15
[⠒] Solc 0.8.15 finished in 1.75s
Compiler run successful
Running 3 tests for contracts/test/modules/HealerModule.t.sol:HealerModuleTest
[PASS] testCannotAddDebt() (gas: 24595)
Logs:
  Cannot add to debt
[PASS] testCannotRemoveCollateral() (gas: 24558)
Logs:
  Cannot remove collateral
[PASS] testHeal() (gas: 606394)
Logs:
  Can add collateral and/or repay debt to a given vault
Test result: ok. 3 passed; 0 failed; finished in 12.16s
```

### CODE REVIEW

**Review by alcueca — APPROVED** [review]

**Review by aniemerg — APPROVED** [review]

**Comment by Sabnock01** [comment]
Proposed: `0x8a9262C7C6eC9bb143Eb68798AdB377c95F47138`

**Comment by Sabnock01** [comment]
Proposal hash: `0x634a2cfdc1be68b139d862ecf1ab229b80f5f5bc9b00dad95aea6016a1eb7f2c`

**Comment by Sabnock01** [comment]
Tenderly fork approve and execute: https://dashboard.tenderly.co/Yield/v2/fork/a4bc4fae-13c3-4fd5-b1aa-c7367deefbac

**Comment by alcueca** [comment]
The proposal tx hash is above, the hashed proposal is `0x2b48aa0a73068a838ed729b09883a85bb0e398a7ce7e89664c36a391a2e94a3a`

**Comment by alcueca** [comment]
[Proposal verification](https://www.notion.so/YPP-50-Healer-Module-0f782b6607cf4820b7bc3baaea7ce6c4)

**Comment by Sabnock01** [comment]
Execution tx hash: `[0xde8fc165071324a6261e3d609f766ede353b35deae6fe3eec667c168dc8032a0](https://etherscan.io/tx/0xde8fc165071324a6261e3d609f766ede353b35deae6fe3eec667c168dc8032a0)`

**Pull request merged**
