### PR TITLE
YP-67: Roll Mar 23-Arbitrum

### PR DESCRIPTION
**Pull request by Sabnock01**
# Proposal
Activate the DAI, USDC, and ETH March series on Arbitrum mainnet using yieldspace-tv, and roll the respective strategies (YSETH6MMS, YSDAI6MMS, YSUSDC6MMS) from September to March.

# Background 
On September 22nd 2022 all September series matured, and the strategies stopped accruing fees. New yieldspace-tv pools are going to be used for the March series.

# Details
The steps are: 
    1. Deploy new fyTokens and Non-tv pools.
    2. Activate the March series
    3. Governance proposal
          i. Orchestrate pools
         ii. Add new series
        iii. Add ilks to the new series
         iv. Initialize new pools
          v. Roll the strategies to the next pool

```
/// @notice Time stretch to be set in the PoolFactory prior to pool deployment
/// @param series identifier (bytes6 tag)
/// @param time stretch (64.64)
export const timeStretch: Map<string, BigNumber> = new Map([
  [FYETH2303, ONE64.div(secondsInOneYear.mul(25))],
  [FYDAI2303, ONE64.div(secondsInOneYear.mul(45))],
  [FYUSDC2303, ONE64.div(secondsInOneYear.mul(55))],
])

/// @notice Sell base to the pool fee, as fp4
export const g1: number = 9000

/// @notice Deploy fyToken series
/// @param series identifier (bytes6 tag)
/// @param underlying identifier (bytes6 tag)
/// @param Address for the chi oracle
/// @param Address for the related Join
/// @param Maturity in unix time (seconds since Jan 1, 1970)
/// @param Name for the series
/// @param Symbol for the series
export const fyTokenData: Array<[string, string, string, string, number, string, string]> = [
  [FYETH2303, ETH, protocol.get(ACCUMULATOR) as string, joins.get(ETH) as string, EOMAR23, 'FYETH2303', 'FYETH2303'],
  [FYDAI2303, DAI, protocol.get(ACCUMULATOR) as string, joins.get(DAI) as string, EOMAR23, 'FYDAI2303', 'FYDAI2303'],
  [
    FYUSDC2303,
    USDC,
    protocol.get(ACCUMULATOR) as string,
    joins.get(USDC) as string,
    EOMAR23,
    'FYUSDC2303',
    'FYUSDC2303',
  ],
]

/// @notice Deploy plain YieldSpace pools
/// @param pool identifier, usually matching the series (bytes6 tag)
/// @param base address
/// @param fyToken address
/// @param time stretch, in 64.64
/// @param g1, in 64.64
export const nonTVPoolData: Array<[string, string, string, BigNumber, number]> = [
  [
    FYETH2303,
    assets.get(ETH) as string,
    newFYTokens.get(FYETH2303) as string,
    timeStretch.get(FYETH2303) as BigNumber,
    g1,
  ],
  [
    FYDAI2303,
    assets.get(DAI) as string,
    newFYTokens.get(FYDAI2303) as string,
    timeStretch.get(FYDAI2303) as BigNumber,
    g1,
  ],
  [
    FYUSDC2303,
    assets.get(USDC) as string,
    newFYTokens.get(FYUSDC2303) as string,
    timeStretch.get(FYUSDC2303) as BigNumber,
    g1,
  ],
]

/// @notice Pool initialization parameters
/// @param pool identifier, usually matching the series (bytes6 tag)
/// @param amount of base to initialize pool with
export const poolsInit: Array<[string, BigNumber]> = [
  [FYETH2303, WAD.div(10)],
  [FYDAI2303, WAD.mul(100)],
  [FYUSDC2303, ONEUSDC.mul(100)],
]

/// @notice Ilks to accept for series
/// @param series identifier (bytes6 tag)
/// @param newly accepted ilks (array of bytes6 tags)
export const seriesIlks: Array<[string, string[]]> = [
  [FYETH2303, [ETH, DAI, USDC]],
  [FYDAI2303, [ETH, DAI, USDC]],
  [FYUSDC2303, [ETH, DAI, USDC]],
]

/// Parameters to roll each strategy
/// @param strategyId
/// @param nextSeriesId
/// @param buffer Amount of base sent to the Roller to make up for market losses when using a flash loan for rolling
/// @param lender ERC3156 flash lender used for rolling
/// @param fix If true, transfer one base wei to the pool to allow the Strategy to start enhanced TV pools
export const rollData: Array<[string, string, BigNumber, string, boolean]> = [
  [YSETH6MMS, FYETH2303, ZERO, ZERO_ADDRESS, false],
  [YSDAI6MMS, FYDAI2303, ZERO, ZERO_ADDRESS, false],
  [YSUSDC6MMS, FYUSDC2303, ZERO, ZERO_ADDRESS, false],
]
```

### CODE REVIEW

**Comment by Sabnock01** [comment]
Proposal hash `0x92ab7d9549461d38f8e35e535e9495be5f2e1c57d458c0bc9628b4fd2a3dab90`
Proposal tx hash `0xde3efb4366ac8eea04a1a95e0eb89d05ad131d030aa14b6dd6f17543a97ab831`

**Comment by Sabnock01** [comment]
Tenderly fork with approve and execute: https://dashboard.tenderly.co/Yield/v2-arbitrum/fork/5bd78733-eba2-40a5-ade3-e8d8d6051f42

**Review by alcueca — APPROVED** [review]
There was a bug, fortunately harmless.

**Comment by alcueca** [comment]
[Proposal execution analysis](https://www.notion.so/Proposals-c8fc707f426a4c0eaa3a17dcaec6b330?p=fb7d90afb3ed47308294b42ec5e1d460&showMoveTo=true)

**Comment by Sabnock01** [comment]
New Tenderly fork with approve and execute: https://dashboard.tenderly.co/Yield/v2/fork/65c00c35-64ba-4b87-a622-b1f0df4867a9

**Comment by Sabnock01** [comment]
Execution tx hash: `0x1dfb078fe07df3526286395b9994e3ecb4ac9d6791f6310e2864958519929dfd`

**Pull request merged**
