### PR TITLE
Add Egill as a developer

### PR DESCRIPTION
**Pull request by alcueca**
# Proposal
Give developer roles on mainnet and arbitrum to 0x02f73B54ccfBA5c91bf432087D60e4b3a781E497, controlled by @egillh210.

# Background
Contango are building on top of us and a developer role will allow them and us to be more efficient.

# Details

The (addDevelopers)[https://github.com/yieldprotocol/environments-v2/blob/main/scripts/governance/permissions/addDevelopers/addDevelopers.ts] script will be used, with (this input)[https://github.com/yieldprotocol/environments-v2/blob/main/scripts/governance/permissions/addDevelopers/addDevelopers.config.ts].

```
export const newDevelopers: string[] = [
    '0x02f73B54ccfBA5c91bf432087D60e4b3a781E497'
]
```

### CODE REVIEW

**Review by aniemerg — APPROVED** [review]

**Comment by alcueca** [comment]
Mainnet proposal: `0x6c98f785a3a1a79ceeab0fda18ad135c87b2d55292d8dcd6f8e41ee6dc5a1096`
Arbitrum proposal: `0xd7987213f58e3d5a3c93f694b6dd7c5b269c3ca24ce174c34de349f70fefd554`

**Comment by alcueca** [comment]
[Mainnet change diff](https://dashboard.tenderly.co/Yield/v2/fork/cae66351-2d39-44bd-b8e9-677947558fdc/simulation/c8b52067-4026-4859-8943-71f3f49ff1cd/state-diff)
[Arbitrum change diff](https://dashboard.tenderly.co/Yield/v2/fork/1bc96f6b-5329-414c-a0bd-b74402ec350e/simulation/19cb9b55-7ed3-40d1-820b-9a9bf346b1b2/state-diff)

**Comment by alcueca** [comment]
Transaction #6 on the Arbitrum multisig.

**Comment by alcueca** [comment]
[Executed on Arbitrum](https://arbiscan.io/tx/0x59ded615e4ecb324dfcf3878d240a9047952d43ad1d0f25395b9bf1b9e13d1ca)

**Comment by alcueca** [comment]
Mainnet ready for execution on Thu Aug 11 2022 17:31:55 GMT+0100 (Western European Summer Time)

**Comment by alcueca** [comment]
[Executed on mainnet](https://etherscan.io/tx/0x48a6bf4fac4527f15f9bcd38a055ff24d8c0a529a20af53042968eb0f7a02742)

**Pull request merged**
