### PR TITLE
YPP-82: Redeploy `YieldMath.sol`

### PR DESCRIPTION
**Pull request by Sabnock01**
# Proposal
Redeploys latest version of `YieldMath.sol`. 

# Background

The previous version of `YieldMath.sol` had three underflows highlighted [here](https://github.com/yieldprotocol/yieldspace-tv/issues/75) and [here](https://github.com/yieldprotocol/yieldspace-tv/issues/76).

# Details

The [deploy script](https://github.com/yieldprotocol/environments-v2/blob/deploy-new-yieldmath/scripts/governance/redeploy/yieldmath/redeployYieldMath.sh) and its respective [config file](https://github.com/yieldprotocol/environments-v2/blob/deploy-new-yieldmath/scripts/governance/redeploy/yieldmath/redeployYieldMath.mainnet.config.ts).

# Testing

Testing has been done on [here](https://github.com/yieldprotocol/yieldspace-tv/blob/main/src/test/YieldMath.t.sol).

### CODE REVIEW

**Comment by alcueca** [comment]
The testing has actually been a manual verification of the code so far. No testing has been done on the proposal itself. Which is fine, but we can be honest here.

**Review by alcueca — APPROVED** [review]
LGTM

**Comment by Sabnock01** [comment]
Mainnet deployment: https://etherscan.io/tx/0x8c7d1a06d77efdf2dcabed29464ecbcbff63aa4eb66ba40ae06d6d8923b94dca

**Comment by Sabnock01** [comment]
This contract is simply being deployed and doesn't need a governance proposal.

**Pull request closed without merging**
