### PR TITLE
`rETH` as collateral

### PR DESCRIPTION
**Pull request by iamsahu**
# Proposal

Enable `rETH` as a collateral.

# Background

This would allow user to borrow DAI/USDC/ETH against `rETH` as collateral.

# Details

Following steps would be taken to get `rETH` as a collateral:

1. Deploy RETHOracle (no need for governance approval)
2. Deploy joins for the strategy assets (no need for governance approval)
3. Governance Proposal
   1. Orchestrate RETHOracle
   2. Update CompositeOracle Sources
   3. Orchestrate the new join
   4. Add `rETH` tokens as Assets
   5. Make `rETH` token as ilk
   6. Add `rETH` tokens as ilks in series

Here is the configuration

```
export const contractDeployments: ContractDeployment[] = [
  {
    addressFile: 'protocol.json',
    name: RETH_ORACLE,
    contract: 'RETHOracle',
    args: [() => ETH, () => RETH, () => assets.getOrThrow(RETH)!],
  },
  {
    addressFile: 'joins.json',
    name: RETH,
    contract: 'Join',
    args: [() => assets.getOrThrow(RETH)!],
  },
]

export const ilkToETH: Ilk = {
  baseId: ETH,
  ilkId: reth.assetId,
  asset: reth,
  collateralization: {
    baseId: ETH,
    ilkId: reth.assetId,
    oracle: protocol().getOrThrow(RETH_ORACLE)!,
    ratio: 1330000,
  },
  debtLimits: {
    baseId: ETH,
    ilkId: reth.assetId,
    line: 150,
    dust: 1,
    dec: 18,
  },
  auctionLineAndLimit: {
    baseId: ETH,
    ilkId: reth.assetId,
    duration: 3600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.78947368'), // 105 / 133
    max: parseUnits('1000'),
  },
}

export const ilkToDAI: Ilk = {
  baseId: DAI,
  ilkId: reth.assetId,
  asset: reth,
  collateralization: {
    baseId: DAI,
    ilkId: reth.assetId,
    oracle: protocol().getOrThrow(COMPOSITE)!,
    ratio: 1670000,
  },
  debtLimits: {
    baseId: DAI,
    ilkId: reth.assetId,
    line: 250000,
    dust: 1000,
    dec: 18,
  },
  auctionLineAndLimit: {
    baseId: DAI,
    ilkId: reth.assetId,
    duration: 3600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.62874251'), // 105 / 167
    max: parseUnits('1000'),
  },
}

export const ilkToUSDC: Ilk = {
  baseId: USDC,
  ilkId: reth.assetId,
  asset: reth,
  collateralization: {
    baseId: USDC,
    ilkId: reth.assetId,
    oracle: protocol().getOrThrow(COMPOSITE)!,
    ratio: 1670000,
  },
  debtLimits: {
    baseId: USDC,
    ilkId: reth.assetId,
    line: 250000,
    dust: 1000,
    dec: 6,
  },
  auctionLineAndLimit: {
    baseId: USDC,
    ilkId: reth.assetId,
    duration: 3600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.62874251'), // 105 / 167
    max: parseUnits('1000'),
  },
}

export const ilkToFRAX: Ilk = {
  baseId: FRAX,
  ilkId: reth.assetId,
  asset: reth,
  collateralization: {
    baseId: FRAX,
    ilkId: reth.assetId,
    oracle: protocol().getOrThrow(COMPOSITE)!,
    ratio: 1670000,
  },
  debtLimits: {
    baseId: FRAX,
    ilkId: reth.assetId,
    line: 250000,
    dust: 1000,
    dec: 18,
  },
  auctionLineAndLimit: {
    baseId: FRAX,
    ilkId: reth.assetId,
    duration: 3600,
    vaultProportion: parseUnits('0.5'),
    collateralProportion: parseUnits('0.62874251'), // 105 / 167
    max: parseUnits('1000'),
  },
}

export const ilks: Ilk[] = [ilkToETH, ilkToDAI, ilkToUSDC, ilkToFRAX]

export const oracleSources: OracleSource[] = [
  {
    baseId: ETH,
    baseAddress: assets.getOrThrow(ETH)!,
    quoteId: RETH,
    quoteAddress: assets.getOrThrow(RETH)!,
    sourceAddress: protocol().getOrThrow(RETH_ORACLE)!,
  },
]

export const oraclePaths: OraclePath[] = [
  {
    baseId: RETH,
    quoteId: DAI,
    path: [ETH],
  },
  {
    baseId: RETH,
    quoteId: USDC,
    path: [ETH],
  },
  {
    baseId: RETH,
    quoteId: FRAX,
    path: [ETH],
  },
]

export const ethSeries: Series[] = [
  {
    seriesId: FYETH2303,
    fyToken: { assetId: FYETH2303, address: fyTokens.getOrThrow(FYETH2303)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToETH],
  },
  {
    seriesId: FYETH2306,
    fyToken: { assetId: FYETH2306, address: fyTokens.getOrThrow(FYETH2306)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToETH],
  },
]

export const daiSeries: Series[] = [
  {
    seriesId: FYDAI2303,
    fyToken: { assetId: FYDAI2303, address: fyTokens.getOrThrow(FYDAI2303)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToDAI],
  },
  {
    seriesId: FYDAI2306,
    fyToken: { assetId: FYDAI2306, address: fyTokens.getOrThrow(FYDAI2306)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToDAI],
  },
]

export const usdcSeries: Series[] = [
  {
    seriesId: FYUSDC2303,
    fyToken: { assetId: FYUSDC2303, address: fyTokens.getOrThrow(FYUSDC2303)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToUSDC],
  },
  {
    seriesId: FYUSDC2306,
    fyToken: { assetId: FYUSDC2306, address: fyTokens.getOrThrow(FYUSDC2306)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToUSDC],
  },
]

export const fraxSeries: Series[] = [
  {
    seriesId: FYFRAX2303,
    fyToken: { assetId: FYFRAX2303, address: fyTokens.getOrThrow(FYFRAX2303)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToFRAX],
  },
  {
    seriesId: FYFRAX2306,
    fyToken: { assetId: FYFRAX2306, address: fyTokens.getOrThrow(FYFRAX2306)! },
    chiOracle: '',
    pool: reth,
    ilks: [ilkToFRAX],
  },
]

export const newSeries: Series[] = [...ethSeries, ...daiSeries, ...usdcSeries, ...fraxSeries]

```

# Testing

The change has been deployed on a mainnet fork with the following output.

```
+ npx hardhat run --network localhost ./scripts/governance/add/addCollateral/addCompositeCollateral/rocket/../../../../../../shared/deploy.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Reusing rethOracle RETHOracle at: 0xbe18A1B61ceaF59aEB6A9bC81AB4FB87D56Ba167
Reusing RETH Join at: 0x25C0a2F0A077F537Bd11897F04946794c2f6f1Ef
+ npx hardhat run --network localhost ./scripts/governance/add/addCollateral/addCompositeCollateral/rocket/addRETH.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
CompositeMultiOracle: pair: ETH/RETH set to 0xbe18A1B61ceaF59aEB6A9bC81AB4FB87D56Ba167
path: RETH/DAI -> 0x303000000000
path: RETH/USDC -> 0x303000000000
0x25C0a2F0A077F537Bd11897F04946794c2f6f1Ef grantRole(ROOT 0x82375994C79e902286D347C9eDE644eA12659FCC)
join.grantRoles(gov, timelock)
Using asset at 0xae78736Cd615f374D3085123A210448E74Fc6393
Using join at 0x25C0a2F0A077F537Bd11897F04946794c2f6f1Ef
Make asset: RETH: 0xae78736Cd615f374D3085123A210448E74Fc6393,
cloak.add(ladle join and exit RETH)
Adding RETH join to Ladle using 0x25C0a2F0A077F537Bd11897F04946794c2f6f1Ef
Spot oracle for 0x303000000000/0xE03016000000 set to 0xbe18A1B61ceaF59aEB6A9bC81AB4FB87D56Ba167 with ratio 1330000
Witch#setLineAndLimit(ilkId: RETH, baseId: ETH, duration: 3600 seconds, vaultProportion: 0.5, collateralProportion: 0.84, max: 1000.0)
join(RETH).grantRole(exit, witch)
cloak.add(witch exit RETH)
Spot oracle for 0x303100000000/0xE03016000000 set to 0xA81414a544D0bd8a28257F4038D3D24B08Dd9Bb4 with ratio 1670000
Witch#setLineAndLimit(ilkId: RETH, baseId: DAI, duration: 3600 seconds, vaultProportion: 0.5, collateralProportion: 0.75, max: 1000.0)
Witch already has an exit role on join(RETH)
Spot oracle for 0x303200000000/0xE03016000000 set to 0xA81414a544D0bd8a28257F4038D3D24B08Dd9Bb4 with ratio 1670000
Witch#setLineAndLimit(ilkId: RETH, baseId: USDC, duration: 3600 seconds, vaultProportion: 0.5, collateralProportion: 0.75, max: 1000.0)
Witch already has an exit role on join(RETH)
addIlks FYETH2303: RETH
addIlks FYETH2306: RETH
addIlks FYDAI2303: RETH
addIlks FYDAI2306: RETH
addIlks FYUSDC2303: RETH
addIlks FYUSDC2306: RETH
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Proposal: 0xa34337e30f2eb73d6ba4de66709a8a51fffc342182ddca3a189ea03308330e83
Proposing
Developer: 0xC7aE076086623ecEA2450e364C838916a043F9a8

Calldata:
0xca02753a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000003400000000000000000000000000000000000000000000000000000000000000420000000000000000000000000000000000000000000000000000000000000054000000000000000000000000000000000000000000000000000000000000006600000000000000000000000000000000000000000000000000000000000000720000000000000000000000000000000000000000000000000000000000000082000000000000000000000000000000000000000000000000000000000000008e00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000b600000000000000000000000000000000000000000000000000000000000000c200000000000000000000000000000000000000000000000000000000000000d200000000000000000000000000000000000000000000000000000000000000e400000000000000000000000000000000000000000000000000000000000000f80000000000000000000000000000000000000000000000000000000000000104000000000000000000000000000000000000000000000000000000000000011600000000000000000000000000000000000000000000000000000000000001260000000000000000000000000000000000000000000000000000000000000138000000000000000000000000000000000000000000000000000000000000014c000000000000000000000000000000000000000000000000000000000000015c000000000000000000000000000000000000000000000000000000000000016e0000000000000000000000000000000000000000000000000000000000000182000000000000000000000000000000000000000000000000000000000000019200000000000000000000000000000000000000000000000000000000000001a200000000000000000000000000000000000000000000000000000000000001b200000000000000000000000000000000000000000000000000000000000001c200000000000000000000000000000000000000000000000000000000000001d20000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006492b45d9c3030000000000000000000000000000000000000000000000000000000000000e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000be18a1b61ceaf59aeb6a9bc81ab4fb87d56ba16700000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb4000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a460509e5fe030160000000000000000000000000000000000000000000000000000000000303100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000001303000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb4000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a460509e5fe03016000000000000000000000000000000000000000000000000000000000030320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000130300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044de02cde7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082375994c79e902286d347c9ede644ea12659fcc0000000000000000000000000000000000000000000000000000000000000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000084effae35300000000000000000000000000000000000000000000000000000000000000400000000000000000000000003b870db67a45611cf4723d44487eaf398fac51e30000000000000000000000000000000000000000000000000000000000000001f06c2dfc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca86700000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044e665f9e4e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000ae78736cd615f374d3085123a210448e74fc63930000000000000000000000000000000000000000000000000000000000000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4effae35300000000000000000000000000000000000000000000000000000000000000400000000000000000000000006cb18ff2a33e981d1e38a663ca056c0a5265066a0000000000000000000000000000000000000000000000000000000000000002ceae3abd0000000000000000000000000000000000000000000000000000000012e5ff77000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082375994c79e902286d347c9ede644ea12659fcc000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e4f92bcb0d0000000000000000000000006cb18ff2a33e981d1e38a663ca056c0a5265066a0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1efceae3abd0000000000000000000000000000000000000000000000000000000000000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef12e5ff7700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006cb18ff2a33e981d1e38a663ca056c0a5265066a0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004449c29d2be03016000000000000000000000000000000000000000000000000000000000000000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef00000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000848ef6bdfa3030000000000000000000000000000000000000000000000000000000000000e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000be18a1b61ceaf59aeb6a9bc81ab4fb87d56ba1670000000000000000000000000000000000000000000000000000000000144b5000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3030000000000000000000000000000000000000000000000000000000000000e0301600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c43fa3c322e03016000000000000000000000000000000000000000000000000000000000030300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e1000000000000000000000000000000000000000000000000006f05b59d3b200000000000000000000000000000000000000000000000000000ba8478cab54000000000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044de02cde712e5ff770000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c4000000000000000000000000000000000000000000000000000000000000000000000000000000000082375994c79e902286d347c9ede644ea12659fcc000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4f92bcb0d00000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c4000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000100000000000000000000000025c0a2f0a077f537bd11897f04946794c2f6f1ef12e5ff770000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000848ef6bdfa3031000000000000000000000000000000000000000000000000000000000000e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000197b7000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3031000000000000000000000000000000000000000000000000000000000000e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d09000000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c43fa3c322e03016000000000000000000000000000000000000000000000000000000000030310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e1000000000000000000000000000000000000000000000000006f05b59d3b200000000000000000000000000000000000000000000000000000a688906bd8b000000000000000000000000000000000000000000000000003635c9adc5dea0000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000848ef6bdfa3032000000000000000000000000000000000000000000000000000000000000e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000a81414a544d0bd8a28257f4038d3d24b08dd9bb40000000000000000000000000000000000000000000000000000000000197b7000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca867000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a4d3fc152b3032000000000000000000000000000000000000000000000000000000000000e030160000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d09000000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000008d2f5c96bb1f6be04b49bcd869d5af01db4c400000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c43fa3c322e03016000000000000000000000000000000000000000000000000000000000030320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e1000000000000000000000000000000000000000000000000006f05b59d3b200000000000000000000000000000000000000000000000000000a688906bd8b000000000000000000000000000000000000000000000000003635c9adc5dea0000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303030390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001e03016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb770030ff00028b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001e03016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303130390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001e03016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb770031ff00028b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001e03016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb77303230390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001e03016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c88191f8cb8e6d4a668b047c1c8503432c3ca8670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008453eecb770032ff00028b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001e03016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Proposed 0xa34337e30f2eb73d6ba4de66709a8a51fffc342182ddca3a189ea03308330e83
+ npx hardhat run --network localhost ./scripts/governance/add/addCollateral/addCompositeCollateral/rocket/../../../../../../shared/approve.ts
Impersonated 0xd659565b84bcfcb23b02ee13e46cb51429f4558a
Proposal: 0xa34337e30f2eb73d6ba4de66709a8a51fffc342182ddca3a189ea03308330e83
Approving
Approved: 0xa34337e30f2eb73d6ba4de66709a8a51fffc342182ddca3a189ea03308330e83
advancing time by 172800 seconds (2 days) to 1674971106
+ npx hardhat run --network localhost ./scripts/governance/add/addCollateral/addCompositeCollateral/rocket/../../../../../../shared/execute.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Proposal: 0xa34337e30f2eb73d6ba4de66709a8a51fffc342182ddca3a189ea03308330e83
Executing
Estimated gas: 1301137 - ETH Balance: 1.0
Executed 0xa34337e30f2eb73d6ba4de66709a8a51fffc342182ddca3a189ea03308330e83
TxHash: 0x29ffa620667b9d77d55a5f8670b9ecd80329a2737460547c46d855b5ad5cd7b5
+ npx hardhat run --network localhost ./scripts/governance/add/addCollateral/addCompositeCollateral/rocket/../../../../../../shared/standardBorrowingTest.ts
Impersonated 0xC7aE076086623ecEA2450e364C838916a043F9a8
Impersonated 0x7c5aaa2a20b01df027ad032f7a768ac015e77b86
series: 0x303030390000
ilk.ilkId: 0xE03016000000
hardhat-tenderly: Warning: No new contracts have been verified.
  Contract not eligible for verification FYToken, IERC3156FlashBorrower, IERC3156FlashLender, IERC20, IERC20Metadata, ERC20, IERC2612, ERC20Permit, AddressStringUtil, SafeERC20Namer, AccessControl, WDiv, CastU256U128, WMul, WDivUp, CastU256U32, IJoin, IOracle, Constants, IERC5095, IFYToken,
vault: 0x2dda86211f9a9c4888d0a8c8
posting 1272137603343730883 ilk.ilkId out of 12094567835406529930213
borrowing 1000000000000000000 FYETH2303
posted and borrowed
repaying 1000000000000000000 FYETH2303 and withdrawing 1272137603343730883 ilk.ilkId
repaid and withdrawn
Impersonated 0x7c5aaa2a20b01df027ad032f7a768ac015e77b86
series: 0x0030FF00028B
ilk.ilkId: 0xE03016000000
hardhat-tenderly: Warning: No new contracts have been verified.
  Contract not eligible for verification FYToken, IERC3156FlashBorrower, IERC3156FlashLender, AccessControl, IERC20, IERC20Metadata, AddressStringUtil, SafeERC20Namer, WMul, WDivUp, IERC2612, ERC20, ERC20Permit, WDiv, IOracle, IERC5095, IJoin, IFYToken, Constants, CastU256U32, CastU256U128,
vault: 0xbe7ffab9624d3b27cfc35c1a
posting 1272137603343730883 ilk.ilkId out of 12094567835406529930213
borrowing 1000000000000000000 FYETH2306
posted and borrowed
repaying 1000000000000000000 FYETH2306 and withdrawing 1272137603343730883 ilk.ilkId
repaid and withdrawn
Impersonated 0x7c5aaa2a20b01df027ad032f7a768ac015e77b86
series: 0x303130390000
ilk.ilkId: 0xE03016000000
hardhat-tenderly: Warning: No new contracts have been verified.
  Contract not eligible for verification FYToken, IERC3156FlashBorrower, IERC3156FlashLender, IERC20, IERC20Metadata, AddressStringUtil, SafeERC20Namer, AccessControl, WDiv, WMul, IERC2612, ERC20, ERC20Permit, WDivUp, CastU256U128, CastU256U32, IOracle, IERC5095, IJoin, IFYToken, Constants,
vault: 0x7e7917f9f3cced3228e98fd7
posting 1033461622951079415 ilk.ilkId out of 12094567835406529930213
borrowing 1000000000000000000000 FYDAI2303
posted and borrowed
repaying 1000000000000000000000 FYDAI2303 and withdrawing 1033461622951079415 ilk.ilkId
repaid and withdrawn
Impersonated 0x7c5aaa2a20b01df027ad032f7a768ac015e77b86
series: 0x0031FF00028B
ilk.ilkId: 0xE03016000000
hardhat-tenderly: Warning: No new contracts have been verified.
  Contract not eligible for verification FYToken, IERC3156FlashBorrower, IERC3156FlashLender, IERC20, IERC20Metadata, ERC20, IERC2612, ERC20Permit, AccessControl, WDivUp, WMul, AddressStringUtil, SafeERC20Namer, WDiv, CastU256U128, CastU256U32, IOracle, IJoin, IERC5095, IFYToken, Constants,
vault: 0xc8232095d05b169eb920d10e
posting 1033461622951079415 ilk.ilkId out of 12094567835406529930213
borrowing 1000000000000000000000 FYDAI2306
posted and borrowed
repaying 1000000000000000000000 FYDAI2306 and withdrawing 1033461622951079415 ilk.ilkId
repaid and withdrawn
Impersonated 0x7c5aaa2a20b01df027ad032f7a768ac015e77b86
series: 0x303230390000
ilk.ilkId: 0xE03016000000
hardhat-tenderly: Warning: No new contracts have been verified.
  Contract not eligible for verification FYToken, IERC3156FlashBorrower, IERC3156FlashLender, IERC20, IERC20Metadata, ERC20, IERC2612, ERC20Permit, AccessControl, AddressStringUtil, SafeERC20Namer, Constants, WMul, WDivUp, WDiv, CastU256U32, CastU256U128, IOracle, IERC5095, IJoin, IFYToken,
vault: 0x9f392d114430f27ff139a590
posting 1033880335637106666 ilk.ilkId out of 12094567835406529930213
borrowing 1000000000 FYUSDC2303
posted and borrowed
repaying 1000000000 FYUSDC2303 and withdrawing 1033880335637106666 ilk.ilkId
repaid and withdrawn
Impersonated 0x7c5aaa2a20b01df027ad032f7a768ac015e77b86
series: 0x0032FF00028B
ilk.ilkId: 0xE03016000000
hardhat-tenderly: Warning: No new contracts have been verified.
  Contract not eligible for verification FYToken, IERC3156FlashBorrower, IERC3156FlashLender, IERC20, IERC20Metadata, ERC20, IERC2612, ERC20Permit, AccessControl, WMul, AddressStringUtil, SafeERC20Namer, CastU256U32, IOracle, IJoin, IERC5095, IFYToken, CastU256U128, WDivUp, WDiv, Constants,
vault: 0x170772dbfef4279542e4db8f
posting 1033880335637106666 ilk.ilkId out of 12094567835406529930213
borrowing 1000000000 FYUSDC2306
posted and borrowed
repaying 1000000000 FYUSDC2306 and withdrawing 1033880335637106666 ilk.ilkId
repaid and withdrawn
```

### CODE REVIEW

**Comment by iamsahu** [comment]
Proposed: `0x07180d97267a6b230e4fb575b37e55ef7a13ee27142ab51f0f401ffb50855190`

[Here](https://dashboard.tenderly.co/Yield/v2/fork/dddd26db-a00d-4606-91e0-41e96d1f69b0) is the tenderly fork.

**Review by alcueca — APPROVED** [review]
Good to go

**Comment by alcueca** [comment]
[Proposal analysis](https://www.notion.so/YPP-96-rETH-as-collateral-44d2ca4b005745c2a8b7d1fe1643b0df)

**Comment by alcueca** [comment]
@iamsahu, could you please add a link to the execution and then merge?

**Comment by iamsahu** [comment]
[Executed](https://etherscan.io/tx/0xa45e43364f874b98579e8b0be88c3f8587a04b734715dd200c74c14d353cf1cd)

**Pull request merged**
